### ISSUE TITLE
show_prompts parameter not working

### ISSUE THREAD

**Issue by vmonichon** [ManuelRoeder/dynaframe_sync#1]
First let me tell you what a great script this is, really love it !!!

I'm trying to not have the prompt shown, but if I set the parameter to 0, it doesn't seem to make any difference.

Looking at the code I don't see where you do the check on the parameter value, I see the qr code check directly within the call to fit_text():

fit_text(img, prompt, (255, 255, 255), font, url if args.qr == 1 else None)

but the value prompt is passed no  matter what with this value :

alt_txt = child.get_attribute("alt")

through this call:

 edit_image(dest, alt_txt, download_link, args)

Is that a feature you are still working on or am I missing something and it should work? (my python days are pretty far behind me  ;)

Again thank you so much for this! Very cool !

**Comment by vmonichon** [comment]
Changed:

in edit_image:

# text layer
    font = ImageFont.truetype("arial.ttf", 30)
    if prompt == None:
        if args.qr == 1:
            fit_text(img, prompt, (255, 255, 255), font, url if args.qr == 1 else None)
    else:
            fit_text(img, prompt, (255, 255, 255), font, url if args.qr == 1 else None)
    # save and quit

in download_elements:

# edit the image if needed
        if args.show_prompts == 1:
            edit_image(dest, alt_txt, download_link, args)
        else:
            edit_image(dest, None, download_link, args)
        # add new entry with sync flag enabled

There is probably better coding but it did it for me ;)

**Comment by ManuelRoeder** [comment]
Thanks for mentioning the issue, I uploaded a patch to fix it. Have fun!
